name: Tag release

on:
    push:
        branches:
            - main

permissions: {}

jobs:
    tag:
        name: Tag release
        runs-on: ubuntu-26.04
        timeout-minutes: 5
        permissions:
            contents: read
        concurrency:
            group: ${{ github.workflow }}
            cancel-in-progress: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Tag the release
              uses: ./
              with:
                  client-id: ${{ vars.GH_APP_CLIENT_ID }}
                  private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
